### ISSUE TITLE
Become unresponsive for large images larger than 2-3k pixels

### ISSUE THREAD

**Issue by sunguard** [wavetogether/wave_figma#6]

**Comment by sunguard** [comment]
Two ways of fixing it
1. Make faster
1. Make interfaces be responsive

**Comment by JuanArreguin** [comment]
@sunguard Are there any updates here with this, trying to export iOS App Store Screenshots, and it's nearly impossible to export since they need to be 1,242 x 2,688

**Comment by sunguard** [comment]
@JuanArreguin Finally, the exporting speed is enhanced in Version 5. Thank you :)
